name: PafiasFFA
version: '${project.version}'
main: me.pafias.pafiasffa.PafiasFFA
api-version: 1.13
softdepend: [ ProtocolLib, PlaceholderAPI, Citizens ]
authors: [ Pafias ]
description: The best FFA plugin!
commands:
  ffa:
    usage: /ffa [subcommand]
    aliases: [freeforall]
    description: FFA Main Command
  kill:
    usage: /kill [player]
    aliases: []
    description: Kill command
permissions:
  ffa:
    children:
      armorstand:
        default: op
      editstats:
        default: op
      kill:
        default: true
        children:
          others:
            default: op
      kit:
        default: op
        children:
          others:
            default: op
      lobby:
        default: op
        children:
          others:
            default: op
      savekit:
        default: op
      savespawn:
        default: op
      setlobby:
        default: op
      spawn:
        default: op
        children:
          others:
            default: op
      stats:
        default: true
        children:
          others:
            default: true