name: PafiasFFA
version: '${project.version}'
main: me.pafias.pafiasffa.PafiasFFA
api-version: 1.13
softdepend: [ ProtocolLib, PlaceholderAPI, Citizens ]
authors: [ Pafias ]
description: The best FFA plugin!
commands:
  ffa:
    usage: /ffa [subcommand]
    aliases: [ freeforall ]
    description: FFA Main Command
    permission: ffa
  kill:
    usage: /kill [player]
    aliases: [ suicide, die, kys, dead, iwanttodiebecauseimdepressed ]
    description: Kill command
    permission: ffa.kill
permissions:
  ffa:
    children:
      armorstand:
        description: Permission to use the ffa's armorstand subcommand
        default: op
      editstats:
        description: Permission to use the ffa's editstats subcommand
        default: op
      kill:
        description: Permission to use the ffa's kill (sub)command
        default: true
        children:
          others:
            description: Permission to use the ffa's kill (sub)command on other players
            default: op
      kit:
        description: Permission to use the ffa's kit subcommand
        default: op
        children:
          others:
            description: Permission to use the ffa's kit subcommand on other players
            default: op
      lobby:
        description: Permission to use the ffa's lobby subcommand
        default: op
        children:
          others:
            description: Permission to use the ffa's lobby subcommand on other players
            default: op
      savekit:
        description: Permission to use the ffa's savekit subcommand
        default: op
      savespawn:
        description: Permission to use the ffa's savespawn subcommand
        default: op
      setlobby:
        description: Permission to use the ffa's setlobby subcommand
        default: op
      spawn:
        description: Permission to use the ffa's spawn subcommand
        default: op
        children:
          others:
            description: Permission to use the ffa's spawn subcommand on other players
            default: op
      stats:
        description: Permission to use the ffa's stats subcommand
        default: true
        children:
          others:
            description: Permission to use the ffa's stats subcommand on other players
            default: true